# recode by damar
# source : https://github.com/Arya-Blitar22/
port: 7890
socks-port: 7891
mixed-port: 10809
mode: global
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret : ""
bind-address: "*"
external-ui: yacd-gh-pages
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  listen: 127.0.0.1:7894
  use-hosts: true
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - 1.1.1.1
  fallback:
    - https://dns.google/dns-query
proxies:
- name: 1v
  server: 104.18.225.52
  type: vless
  port: 443
  uuid: df93d4b2-1936-4ee7-ab11-c65284a502dd
  tls: true
  skip-cert-verify: true
  servername: cxio.pages.dev
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: cxio.pages.dev
  udp: true

- name: 1L
  server: sogood.linefriends.com
  type: vless
  port: 443
  uuid: df93d4b2-1936-4ee7-ab11-c65284a502dd
  tls: true
  skip-cert-verify: true
  servername: cxio.pages.dev
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: cxio.pages.dev
  udp: true

- name: 2v
  server: vision.ast.my
  type: vless
  port: 443
  uuid: df93d4b2-1936-4ee7-ab11-c65284a502dd
  tls: true
  skip-cert-verify: true
  servername: cxio.pages.dev
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: cxio.pages.dev
  udp: true

- name: 1f
  server: investor.fb.com
  type: vless
  port: 443
  uuid: df93d4b2-1936-4ee7-ab11-c65284a502dd
  tls: true
  skip-cert-verify: true
  servername: cxio.pages.dev
  network: ws
  ws-opts:
    path: /?ed=2048
    headers:
      Host: cxio.pages.dev
  udp: true

- name: 3v
  server: 104.18.225.52
  type: vmess
  port: 443
  uuid: 44301322-f1c6-4f7d-ae91-477db524066a
  alterId: 0
  cipher: auto
  tls: true
  skip-cert-verify: true
  servername: v2ray2.udpgw.com
  network: ws
  ws-opts:
    path: /worryfree
    headers:
      Host: v2ray2.udpgw.com
  udp: true
proxy-groups:
  - name: Damarr
    type: select
    proxies:
      - 1v
      - 1L
      - 2v
      - 1f
      - 3v
      - LOAD-BALANCE
      - BEST-PING
      - FALLBACK
      - DIRECT
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 1v
      - 1L
      - 2v
      - 1f
      - 3v
  - name: BEST-PING
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 300
    tolerance: 50
    proxies:
      - 1v
      - 1L
      - 2v
      - 1f
      - 3v
  - name: FALLBACK
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 300
    proxies:
      - 1v
      - 1L
      - 2v
      - 1f
      - 3v
rule-providers:
  clash:
    type: http
    behavior: domain
    url: https://howdy.id/download/rules/clash.txt
    path: ./providers/rule-provider_clash.yaml
    interval: 86400
rules:
  - MATCH,Damarr
#Start Coy...
